### ISSUE TITLE
Variants data stored per master?

### ISSUE THREAD

**Issue by jenskutilek** [Nagwa-Limited-Community/Glyphs-MATH-Plugin#7]
The readme states

> Glyph → Edit MATH Variants... for editing glyph-level MATH variants, assembly, and extended shape flag. The values are saved per-master and should be edited for each master.

Looking at the code, this doesn’t seem to be the case, as the values are stored in the glyph user data. Can you clarify the intended behaviour?

**Comment by khaledhosny** [comment]
I think the idea was to store some data per master to allow for interpolation (and font variations when the spec gets it), but I probably thought it does not make sense to store assembly data per master since they should be the same across the font and it is just much work to edit them per master (the metrics of the variants and assembly parts can change across masters, but we take it from the layer data already).

**Comment by khaledhosny** [comment]
So apparently the documentation is just wrong, since this data appear to have been saved in the glyph user data since the initial commit (6307fdf3fe40a481c1678794b835ced0c8e71743).

**Comment by khaledhosny** [comment]
Now thinking about this, I think we actually want this to be per layer, since start and end connector lengths are set explicitly and these can change across masters.

It is been over two years and I already forgot much about this code.

**Comment by khaledhosny** [comment]
I’m going to try to put the data in layer, and migrate it from glyph if it is there when the font is opened to not break existing projects.

**Comment by khaledhosny** [comment]
Thinking about this again, I think variants should be kept per glyph, only assemblies need per-layer data (the start and end connector lengths). I think also we will need to interpolate them, like #14.

**Comment by khaledhosny** [comment]
Now only assemblies are per layer, but I haven’t done the interpolation bit.
